version: 0.1
phases:
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - $(aws ecr get-login --no-include-email)

  build:
    commands:
      - echo Build started on `date`
      - docker build -t nginx:latest .
      - docker tag nginx:latest $REPOSITORY_URI
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI
artifacts:
  files:
      - appspec.yaml
      - taskdef.json